name       : perl-html-parser
version    : '3.81'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-3.81.tar.gz : c0910a5c8f92f8817edd06ccfd224ba1c2ebe8c10f551f032587a1fc83d62ff2
homepage   : https://metacpan.org/pod/HTML::Parser
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTML::Parser - HTML parser class
description: |
    Objects of the HTML::Parser class will recognize markup and separate it from plain text (alias data content) in HTML documents. As different kinds of markup and text are recognized, the corresponding event handlers are invoked.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
