name       : perl-html-parser
version    : '3.78'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-3.78.tar.gz : 22564002f206af94c1dd8535f02b0d9735125d9ebe89dd0ff9cd6c000e29c29d
homepage   : https://metacpan.org/pod/HTML::Parser
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTML::Parser - HTML parser class
description: |
    Objects of the HTML::Parser class will recognize markup and separate it from plain text (alias data content) in HTML documents. As different kinds of markup and text are recognized, the corresponding event handlers are invoked.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
