name       : perl-html-parser
version    : '3.76'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-3.76.tar.gz : 64d9e2eb2b420f1492da01ec0e6976363245b4be9290f03f10b7d2cb63fa2f61
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : HTML Parsing Module
description: |
    A perl module to parse html
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
