name       : perl-html-parser
version    : 3.72
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/HTML-Parser-3.72.tar.gz : ec28c7e1d9e67c45eca197077f7cdc41ead1bb4c538c7f02a3296a4bb92f608b
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : HTML Parsing Module
description: |
    A perl module to parse html
builddeps  :
 - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
